language: r
sudo: true
cache: packages

r:
  - oldrel
  - release
  - devel

os:
  - linux
  - osx
  
matrix:
 exclude:
    - r:  devel
      os: osx
    - r:  oldrel
      os: osx

r_packages:
  - covr
  

after_success:
  - Rscript -e 'covr::codecov(type = "all")'
